theme = "catppuccin_mocha"

[editor]
line-number = "relative"
end-of-line-diagnostics = "disable"
color-modes = true
popup-border = "all"
true-color = true

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.indent-guides]
render =  true

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.statusline]
left = ["mode","spinner", "file-base-name", "file-modification-indicator"]
# center = ["file-name"]
right = ["separator", "diagnostics", "selections", "position", "file-encoding", "version-control", "file-type"]
separator = "â”‚"
# mode.normal = "NORMAL"
# mode.insert = "INSERT"
# mode.select = "SELECT"
diagnostics = ["warning", "error"]
workspace-diagnostics = ["warning", "error"]


# helix/config.toml
[keys.normal]
C-g = [
    ":write-all",
    ":insert-output lazygit >/dev/tty",
    ":redraw",
    ":reload-all"
]
